# Generated by Django 4.1.1 on 2022-10-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
