# Generated by Django 4.1.1 on 2022-10-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(max_length=100),
        ),
    ]
